# -*- coding: utf-8 -*-
import sys
import csv
reload(sys)
sys.setdefaultencoding('utf-8')
sys.path.append("..")
import urllib
import unittest
import json
import random
from GlobalVariables import gl
from GlobalVariables import GetParamFromFile as gpff
#import TestData_Online
#import TestData
import TestApprovalsProcess_online
from GlobalVariables import Tools



from HTMLTestRunner import HTMLTestRunner
import unittest

"""if __name__ == '__main__':
    with open('One_ApprovalsProcess_test_report_Online.html', 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title='One ApprovalsProcess Online Env Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(gl.suite)"""
#gpff.get_fields_data_from_csv_file(gpff)

#Tools.add_clonum_from_csv_file(Tools)
#Tools.assign_profile_to_point_user(Tools)
#Tools.create_meta_object_online(Tools)

Tools.create_new_com_meta_schema_with_ci_env_meta(Tools)   #Campaign    MechatAccountID  (MechatAccount)











