# -*- coding: utf-8 -*-
"""解决'ascii' codec can't decode byte 0xe6"""
import sys
import csv
reload(sys)
sys.setdefaultencoding('utf-8')
sys.path.append("..")
import urllib
import unittest
import json
import random
from GlobalVariables import gl
from GlobalVariables import GetParamFromFile as gpff
from GlobalVariables import Tools
import TestLayOutAll as tloa
reload(sys)
sys.setdefaultencoding('utf-8')

"""add test sutie,import order is run order"""
#from TestAccount import TestAccountSignup
#from TestAccount import TestAccountResetPwd
from TestAccount import TestAccountSignin
from TestTenant import TestTenant
#from TestTenantSignOut import TestTenantSignOut

from HTMLTestRunner import HTMLTestRunner
import unittest

"""if __name__ == '__main__':
    with open('HTMLReport.html', 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title='Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(gl.suite)"""

#gpff.get_fields_data_from_csv_file(gpff)

#Tools.add_clonum_from_csv_file(Tools)
#Tools.assign_profile_to_point_user(Tools)
tloa.create_layout_json(tloa)
