# -*- coding: utf-8 -*-
"""解决'ascii' codec can't decode byte 0xe6"""
import sys
import csv
reload(sys)
sys.setdefaultencoding('utf-8')
sys.path.append("..")
import urllib
import unittest
import json
import random
from GlobalVariables import gl
from GlobalVariables import GetParamFromFile as gpff
from GlobalVariables import Tools
from TestJudge import TestJudgeAll
import TestEnvMetaCopyTools
reload(sys)
sys.setdefaultencoding('utf-8')

from HTMLTestRunner import HTMLTestRunner
import unittest

"""if __name__ == '__main__':
    with open('Judge_test_report_Online.html', 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title='Judge Online Env Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(gl.suite)"""
#from TestAccount import TestAccountSignup
#from TestAccount import TestAccountResetPwd
from TestAccount import TestAccountSignin
from TestTenant import TestTenant
#from TestTenantSignOut import TestTenantSignOut

from HTMLTestRunner import HTMLTestRunner
import unittest

#gpff.get_fields_data_from_csv_file(gpff)
#Tools.create_meta_object_online(Tools)
#Tools.create_new_com_meta_schema_with_ci_env_meta(Tools)
#Tools.get_meta_from_online_env(Tools)
#Tools.add_clonum_from_csv_file(Tools)
#Tools.add_profile_FLA(Tools)
#Tools.add_profile_OLA(Tools)
#Tools.add_profile_FLA(Tools)
#Tools.assign_profile_to_point_user(Tools)
TestEnvMetaCopyTools.create_judge_profile_by_ci_profile()
